[package]
name = "lnp2p"
version = "0.6.0-beta.2"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "LN P2P Library: rust implementation of lightning network peer protocols (BOLT-1, 2, 7, 9, Bifrost)"
repository = "https://github.com/LNP-BP/lnp-core"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "lightning", "lnp", "lnp-bp", "bifrost"]
categories = ["cryptography::cryptocurrencies", "network-programming"]
readme = "../README.md"
edition = "2021"
rust-version = "1.56.1"

[lib]
name = "lnp2p"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
amplify = { version = "3.9.1", features = ["hex", "rand"] }
lnpbp = "0.5.0"
bp-core = "0.5.0"
strict_encoding = { version = "1.7.9", optional = true, features = ["chrono"] }
lightning_encoding = "0.5.13"
descriptor-wallet = "0.5.0"
miniscript = "6.0.1"
bitcoin = "0.27.1"
internet2 = { version = ">=0.5.18", default-features = false, features = ["derive"] }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }
lazy_static = "1.4"
chrono = "0.4"

[features]
default = ["legacy"]
all = ['bifrost', "serde"]
legacy = []
bifrost = ["strict_encoding"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/use-serde"]
